### ISSUE TITLE
AWSLambdaFullAccess does not exist or is not attachable

### ISSUE THREAD

**Issue by aktur** [cnunciato/photomap#1]
Triggered by manning pulumi in action video I wanted to check this little project. During deployment I hit an error
```
  aws:iam:RolePolicyAttachment (apid7435936-32be53a2):
    error: 1 error occurred:
    	* Error attaching policy arn:aws:iam::aws:policy/AWSLambdaFullAccess to IAM Role apid7435936-190bccf: NoSuchEntity: Policy arn:aws:iam::aws:policy/AWSLambdaFullAccess does not exist or is not attachable.
    	status code: 404, request id: ea76556f-d3ef-424d-9097-5461e0a95c96
```
I've checked in console and it seems that this role is now `arn:aws:iam::aws:policy/AWSLambda_FullAccess`
Is it possible to change this or it is fully controlled by Pulumi?

**Comment by cnunciato** [comment]
Thanks for posting this question! These APIs have definitely changed since I recorded this session — I’ll take a look and report back.

**Comment by cnunciato** [comment]
Sorry for the delay! Busy summer's been getting away from me. 

I was able to get a good repro for this, so I've updated all of the dependencies to their latest versions, and verified everything still works as expected:

![image](https://user-images.githubusercontent.com/274700/183217665-9a9deeae-a0ab-4afc-8067-ff2336249692.png)

Thank you again for the report! Incidentally, the video you saw was made to promote Pulumi in Action, which I'm no longer working on -- but my "new" (post-Manning, still-in-progress) book is here: <https://thepulumibook.com>. Take a look, and if you'd like a free copy, shoot me an email and I'll get you a magic link! 😄 Cheers.

**Comment by aktur** [comment]
Hi Christian,

Thank you for the update. I’m eager to try Pulumi and for sure would appreciate your ‘magic’ link :). By the way, do you know any example to use Pulumi with deployment to Databricks? I’m currently heavily using this environment and their rest API and even CLI is kind of PITA when you do it in CDK.

Kind regards,

***@***.***
